import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Regular"}
size = 15

[window]
padding = {x = 9, y = 9}

[selection]
save_to_clipboard = true 
