import = [
  "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[shell]
program = "/bin/zsh"
# args = ["-l", "-c", "-2", "tmux a -t code || tmux new -s code"]
# This basically makes it so that tmux starts right at the start

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
padding = {x = 8, y = 8}
position = {x = 200, y = 100}
startup_mode = "Maximized"

[selection]
save_to_clipboard = true 
